-- AlterTable
ALTER TABLE "Admin" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Advantage" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL;

-- AlterTable
ALTER TABLE "AffiliatedCompany" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "addressUz" DROP NOT NULL,
ALTER COLUMN "addressEn" DROP NOT NULL,
ALTER COLUMN "descUz" DROP NOT NULL,
ALTER COLUMN "descEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "AnniversarySlider" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Appeal" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Brand" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "CRM" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Catalog" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Category" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ComplianceReport" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Dealer" ALTER COLUMN "regionUz" DROP NOT NULL,
ALTER COLUMN "regionEn" DROP NOT NULL,
ALTER COLUMN "nameUz" DROP NOT NULL,
ALTER COLUMN "nameEn" DROP NOT NULL,
ALTER COLUMN "addressUz" DROP NOT NULL,
ALTER COLUMN "addressEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "History" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "descUz" DROP NOT NULL,
ALTER COLUMN "descEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Management" ALTER COLUMN "nameUz" DROP NOT NULL,
ALTER COLUMN "nameEn" DROP NOT NULL,
ALTER COLUMN "positionUz" DROP NOT NULL,
ALTER COLUMN "positionEn" DROP NOT NULL,
ALTER COLUMN "receptionUz" DROP NOT NULL,
ALTER COLUMN "receptionEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Menu" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "News" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "descUz" DROP NOT NULL,
ALTER COLUMN "descEn" DROP NOT NULL,
ALTER COLUMN "contentUz" DROP NOT NULL,
ALTER COLUMN "contentEn" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Page" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "contentUz" DROP NOT NULL,
ALTER COLUMN "contentEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Partner" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "contentUz" DROP NOT NULL,
ALTER COLUMN "contentEn" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Setting" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Slider" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TechSection" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Vacancy" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "titleUz" DROP NOT NULL,
ALTER COLUMN "titleEn" DROP NOT NULL,
ALTER COLUMN "deptUz" DROP NOT NULL,
ALTER COLUMN "deptEn" DROP NOT NULL,
ALTER COLUMN "locUz" DROP NOT NULL,
ALTER COLUMN "locEn" DROP NOT NULL;
